[project]
name = "pdf-chat"
version = "0.1.0"
description = "An Rag based Chat with pdf application"
authors = [
    {name = "Octahedron-apple",email = "bhavya1singh1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pypdf",
    "langchain-core",
    "langchain-openai",
    "langchain-community",
    "faiss-cpu",
    "python-dotenv"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
pdfchat = "pdf_chat.cli:main"
