[project]
name = "pypdfchat"
version = "0.1.0"
description = "An RAG based Chat with PDF application"
authors = [
    {name = "Octahedron-apple", email = "bhavya1singh1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypdf",
    "langchain-core",
    "langchain-classic",
    "langchain-openai",
    "langchain-ollama",
    "langchain-community",
    "faiss-cpu",
    "python-dotenv"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pypdfchat = "pypdfchat.cli:main"
